### ISSUE TITLE
快来解决bug啦

### ISSUE THREAD

**Issue by Tryking** [gnaixx/hidex-hack#2]
StringIds.java里面：
`for (int i = 0; i < size; i++) {`
`            int dataOff = reader.readUint();`
`            Uleb128 utf16Size = getUleb128(dexBuff, dataOff);`
`           byte[] data = subdex(dexBuff, dataOff + utf16Size.getLength(), utf16Size.getIntValue());`
`          StringId stringId = new StringId(dataOff, utf16Size, data);`
`            stringIds[i] = stringId;`
  }`
这里，字符串是以MUTF-8的格式存储的，MUTF-8头部存放的是由uleb128编码的字符的个数，并不一定占用2个字节，直接read.readUint()是不是不恰当？对于后面的字符，每个字符都是用UTF-8编码的，和uleb不一定是对应的，这里应该是刚好都是英文，只用一个字节，恰好钻了个空子。作者怎么看？

**Comment by gnaixx** [comment]
size of this string, in UTF-16 code units (which is the "string length" in many systems). That is, this is the decoded length of the string. (The encoded length is implied by the position of the 0 byte.)

卧槽 这段话没看懂，明明保存的格式是utf-8，为啥上面又说的utf-16。

**Comment by gnaixx** [comment]
有问题的不是 readUint() ,是subdex() 。readUint() 是获取数据的偏移。但是string数据是用utf-8保存的，所以长度不能用utf16size.getIntValue 获取。你说的对这里都是英文所以都是占一个字节，但是像中文就占用了三个字节，所以直接用utf16size.getIntValue读取有问题呢
新增了一个犯法 getUtf-8 应该没有问题了

**Comment by Tryking** [comment]
获取数据偏移是没问题，但是表示数据偏移的这个数据不一定占用2个字节，直接用readUint()应该不对，因为保存string个数的这个数据是由uleb128编码的，因此要用读取uleb128的方式来进行读取。

**Comment by gnaixx** [comment]
偏移量是 uint类型的，utf16_size才是 uleb128 类型的。可以看下面的010Editor
![image](https://cloud.githubusercontent.com/assets/9268187/23328998/b40ed920-fb69-11e6-94c7-c2b5e6b423f2.png)

**Comment by Tryking** [comment]
对对，我看错了，我以为刚开始就是字符串的描述了。
